CREATE TABLE study_assessments (
                                   id INTEGER PRIMARY KEY AUTOINCREMENT,
                                   quartile TEXT NOT NULL,
                                   course_name TEXT NOT NULL,
                                   course_code TEXT NOT NULL,
                                   exam_name TEXT NOT NULL,
                                   exam_date TEXT NOT NULL,
                                   earnable_credits REAL NOT NULL,
                                   grade REAL,
                                   sort_order INTEGER NOT NULL,
                                   created_at TEXT NOT NULL,
                                   updated_at TEXT NOT NULL
);

INSERT INTO study_assessments (
    quartile,
    course_name,
    course_code,
    exam_name,
    exam_date,
    earnable_credits,
    grade,
    sort_order,
    created_at,
    updated_at
) VALUES
      (
          'S1 Q1',
          'PCO',
          'CU75001V3',
          'First Exam Opportunity',
          '03-10-2025',
          2.5,
          9.3,
          1,
          datetime('now'),
          datetime('now')
      ),
      (
          'S1 Q1',
          'PBA',
          'CU75003V1',
          'Casustoets PBA',
          '30-10-2025',
          5,
          9.7,
          2,
          datetime('now'),
          datetime('now')
      ),
      (
          'S1 Q1',
          'CSB',
          'CU75002V1',
          'Schriftelijke Kennistoets',
          '31-10-2025',
          5,
          7.3,
          3,
          datetime('now'),
          datetime('now')
      ),
      (
          'S1 Q2',
          'OOP',
          'CU75004V1',
          'Presentation',
          'Week S1.15',
          5,
          7.5,
          4,
          datetime('now'),
          datetime('now')
      ),
      (
          'S1 Q2',
          'OOP',
          'CU75004V1',
          'Written Knowledge Test',
          'Week S1.20',
          5,
          9.6,
          5,
          datetime('now'),
          datetime('now')
      ),
      (
          'S2 Q3',
          'Framework Project 1',
          'CU75080V3',
          'On-Site Case Study Exam',
          'Week S2.8',
          5,
          9.2,
          6,
          datetime('now'),
          datetime('now')
      ),
      (
          'S2 Q3',
          'Framework Project 1',
          'CU75080V3',
          'Presentation (Group)',
          'Week S2.8',
          5,
          5.5,
          7,
          datetime('now'),
          datetime('now')
      ),
      (
          'S2 Q4',
          'Framework Project 2',
          'CU75011V4',
          'Presentation (Group)',
          'Week S2.18',
          2.5,
          NULL,
          9,
          datetime('now'),
          datetime('now')
      ),
      (
          'S2 Q4',
          'Framework Project 2',
          'CU75011V4',
          'Portfolio (Individual Project Assessment)',
          'Week S2.15 - S2.20',
          5,
          NULL,
          10,
          datetime('now'),
          datetime('now')
      ),
      (
          'S2 Q4',
          'Framework Project 2',
          'CU75011V4',
          'Portfolio (IT Development Portfolio)',
          'Week S2.18',
          5,
          NULL,
          11,
          datetime('now'),
          datetime('now')
      ),
      (
          'S2 Q4',
          'BUB',
          'CU75081V1',
          'Video (Individual Assignment)',
          'Week S2.19',
          2.5,
          NULL,
          12,
          datetime('now'),
          datetime('now')
      ),
      (
          'S2 Q4',
          'PPD-E',
          'CU75068V3',
          'Criterium Focused Interview',
          'Week S2.11 - S1.8 (Y2)',
          12.5,
          NULL,
          13,
          datetime('now'),
          datetime('now')
      );