CREATE TABLE projects (
                          id INTEGER PRIMARY KEY AUTOINCREMENT,
                          title TEXT NOT NULL,
                          description TEXT NOT NULL,
                          long_description TEXT NOT NULL,
                          tech_json TEXT NOT NULL,
                          status TEXT NOT NULL,
                          completed_at TEXT NOT NULL,
                          category TEXT NOT NULL,
                          image TEXT NOT NULL,
                          url TEXT NOT NULL,
                          sort_order INTEGER NOT NULL,
                          created_at TEXT NOT NULL,
                          updated_at TEXT NOT NULL
);

INSERT INTO projects (
    title,
    description,
    long_description,
    tech_json,
    status,
    completed_at,
    category,
    image,
    url,
    sort_order,
    created_at,
    updated_at
) VALUES
      (
          'Portfolio Website',
          'A responsive personal portfolio website showcasing my projects, skills, blog, profile, and study progress.',
          'A responsive personal portfolio website with dynamic content management, admin-only editing, blog publishing workflow, profile sections, and a study dashboard.',
          '["PHP", "Twig", "SQLite", "JavaScript"]',
          'Completed',
          '2025-04-18',
          'Web Development',
          '/uploads/blog/blog_6a1d5d359a3779.75266393.png',
          '/profile',
          1,
          datetime('now'),
          datetime('now')
      ),
      (
          'Blog System',
          'A blog publishing workflow with create, edit, delete, draft and published status, and image uploads.',
          'A complete blog management system where an admin can create posts, upload images, edit content, switch between draft and published status, and delete posts safely.',
          '["PHP", "Twig", "SQLite", "CSRF", "File Uploads"]',
          'Completed',
          '2025-05-02',
          'CMS Feature',
          '/uploads/blog/blog_6a1d5d359a3779.75266393.png',
          '/blog',
          2,
          datetime('now'),
          datetime('now')
      ),
      (
          'Study Dashboard',
          'A dashboard that stores assessments in the database and calculates earned credits based on grades.',
          'A study progress dashboard that stores assessment data in SQLite, allows grade editing, and automatically calculates earned study credits and NBSA progress.',
          '["PHP", "Twig", "SQLite", "PHPUnit", "JavaScript"]',
          'Completed',
          '2025-05-24',
          'Study Progress',
          '/uploads/blog/blog_6a1d5d359a3779.75266393.png',
          '/dashboard',
          3,
          datetime('now'),
          datetime('now')
      ),
      (
          'Authentication System',
          'A secure login system with password hashing, authorization middleware, and CSRF protection.',
          'A secure authentication and authorization system that supports login, logout, password hashing, role-based access control, admin-only routes, and CSRF protection for POST requests.',
          '["PHP", "SQLite", "Password Hashing", "Middleware", "CSRF"]',
          'Completed',
          '2025-05-26',
          'Security',
          '/uploads/blog/blog_6a1d5d359a3779.75266393.png',
          '/login',
          4,
          datetime('now'),
          datetime('now')
      ),
      (
          'Editable Profile',
          'A profile page where professional biography, programming skills, and languages can be managed.',
          'A database-driven profile page that allows an administrator to update professional biographical information, programming skills, and language knowledge through a protected edit form.',
          '["PHP", "Twig", "SQLite", "Admin Authorization"]',
          'Completed',
          '2025-05-28',
          'Content Management',
          '/uploads/blog/blog_6a1d5d359a3779.75266393.png',
          '/profile',
          5,
          datetime('now'),
          datetime('now')
      ),
      (
          '3D Laptop Project Showcase',
          'An interactive Three.js laptop that allows visitors to explore projects through a virtual laptop screen.',
          'An innovative interactive project showcase built with Three.js. Visitors can rotate the laptop, enter fullscreen mode, open and close the screen, and browse project data loaded dynamically from a RESTful API.',
          '["Three.js", "JavaScript", "WebGL", "REST API", "Canvas Texture"]',
          'Completed',
          '2026-06-02',
          'Innovation',
          '/uploads/blog/blog_6a1d5d359a3779.75266393.png',
          '/projects-3d',
          6,
          datetime('now'),
          datetime('now')
      );